# 日本の祝日データを更新します

name: Update Holidays

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00

jobs:

  update_holidays:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Update Holidays
        run: |
          go run ./hack/import/import_japan_holidays.go > ./holidays.go
          go fmt ./holidays.go

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@b1ddad2c994a25fbc81a28b3ec0e368bb2021c50 # v6.0.0
        with:
          add-paths: holidays.go
          commit-message: Update holidays on $(date +'%Y-%m-%d')
          branch: update-holidays
          title: Update holidays
          reviewers: GarupanOjisan
